event_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'users'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

users/urls.py
"""URLs"""

from django.urls import path, include
from . import views
from .views import home, signup

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('signup/', signup, name="signup"),
    path('event/<int:id>/', views.event_detail, name='event_detail'),
    path("events_by_city/", views.events_by_city, name="events_by_city"),
    path('events/<str:event_tag>/', views.events_by_tag, name='events_by_tag'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile_view, name='profile'),
]

users/models.py
"""Table Creation"""

import datetime
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    """ Event Details """

    event_tag = models.CharField(max_length=200)
    event_name = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField(default=datetime.time(0, 0), null=True, blank=True)
    image_url = models.URLField(max_length=200)
    city = models.CharField(max_length=50)
    location = models.TextField()
    description = models.TextField(default="no description")
    booking_url = models.URLField(
        max_length=200,
        default=(
            "https://insider.in/event/u1s-long-drive-live-in-concert-coimbatore"
            "-oct12-2024/buy-page/shows/65cda8bb66eb4b000aaf16e9"
        ),
    )

    def __str__(self):
        """ returning the event_name """
        return str(self.event_name)

class UserProfile(models.Model):
    """ User Profile Details """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    first_name = models.CharField(max_length=10, blank=True, null=True)
    last_name = models.CharField(max_length=10, blank=True, null=True)
    search_history = models.TextField(blank=True, null=True)  # To store search queries as text
    interaction = models.TextField(blank=True, null=True)  # To store event interactions

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        """ Handle image replacement or removal """
        try:
            old_profile = UserProfile.objects.get(id=self.id)
            if old_profile.profile_picture and old_profile.profile_picture != self.profile_picture:
                old_profile.profile_picture.delete(save=False)
        except UserProfile.DoesNotExist:
            pass

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """ Delete the profile pricture if it exists """
        if self.profile_picture:
            self.profile_picture.delete(save=False)
        super().delete(*args, **kwargs)

users/forms.py
''' Creation and Updation of User and User Profile '''
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class CustomUserCreationForm(UserCreationForm):
    """ Customised User Creation Form to add EmailField """
    email = forms.EmailField(required=True, max_length=254)

    class Meta:
        """ Fields in User Form """
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        ''' Ensuring that email is unique for each user '''
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with that email already exists.")
        return email


# Form for UserProfile model fields
class UserProfileForm(forms.ModelForm):
    """ Customised User Profile """
    class Meta:
        """ Fields in User Profile """
        model = UserProfile
        fields = ['profile_picture', 'first_name', 'last_name', 'location']

users/views.py
""" views """

from collections import Counter
import random
from django.db.models import Q
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Event, UserProfile
from .forms import CustomUserCreationForm, UserProfileForm


def profile_view(request):
    """User Profile Updation"""
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile.objects.create(user=request.user)

    if request.method == "POST":
        user_form = CustomUserCreationForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid():
            user_form.username.save()  # This will save username and email
            return redirect("users:profile")
        if profile_form.is_valid():
            profile_form.save()  # This will save first & last name, profile_picture and location
            return redirect("users:profile")
    else:
        user_form = CustomUserCreationForm(instance=request.user)
        profile_form = UserProfileForm(instance=profile)

    return render(
        request,
        "profile.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "profile_picture": profile.profile_picture,
        },
    )


def recommend_events(user):
    """Generate a list of recommended events based on user activity."""
    # Get user profile
    try:
        user_profile = user.userprofile
    except UserProfile.DoesNotExist:
        return Event.objects.none()  # Return empty queryset if no profile found

    # Parse search history and interaction data
    search_keywords = (
        user_profile.search_history.split(", ") if user_profile.search_history else []
    )
    interaction_keywords = (
        user_profile.interaction.split(", ") if user_profile.interaction else []
    )

    # Combine and count occurrences
    all_keywords = search_keywords + interaction_keywords
    keyword_counter = Counter(all_keywords)

    # Create a Q object to match any of the keywords
    q_objects = Q()
    for keyword in keyword_counter:
        q_objects |= Q(event_name__icontains=keyword) | Q(event_tag__icontains=keyword)

    # Query for events matching the user's preferences
    recommended_events = Event.objects.filter(q_objects).distinct()

    # Rank events based on keyword frequency
    ranked_events = sorted(
        recommended_events,
        key=lambda event: sum(
            keyword_counter.get(tag, 0) for tag in [event.event_name, event.event_tag]
        ),
        reverse=True,
    )

    top_ranked_events = random.sample(ranked_events, 5)

    return top_ranked_events


def home(request):
    """Home page with all the events"""
    # Retrieve all events and orders by date
    events = Event.objects.all().order_by("date")[:5]
    # Retrieve all unique event tags
    tags = Event.objects.values("event_tag")
    # Retrieve all unique city names
    cities = Event.objects.values_list("city", flat=True).distinct()

    tag_events = {}
    for tag in tags:
        tag_events[tag["event_tag"]] = Event.objects.filter(event_tag=tag["event_tag"])[:5]

    # Generate recommendations if the user is authenticated
    recommended_events = []
    if request.user.is_authenticated:
        recommended_events = recommend_events(request.user)

    return render(
        request,
        "home.html",
        {
            "events": events,
            "events_by_tag": tag_events,
            "cities": cities,
            "recommended_events": recommended_events,
        },
    )


def events_by_city(request):
    """Display events for a specific city"""

    # Get the city from the GET parameters
    selected_city = request.GET.get("city")

    if not selected_city:
        # Redirect to home if no city is selected
        return redirect("users:home")

    # Retrieve events for the selected city and ordering them by date
    events = Event.objects.filter(city=selected_city).order_by("date")

    # Set up pagination
    paginator = Paginator(events, 6)
    page_number = request.GET.get("page")
    events = paginator.get_page(page_number)

    return render(
        request,
        "events_by_city.html",
        {"events": events, "selected_city": selected_city},
    )


def event_detail(request, id):
    """Event Detail page which returns the details of the event"""
    event = Event.objects.get(id=id)

    # Store event interaction in UserActivity
    if request.user.is_authenticated:
        user_activity, created = UserProfile.objects.get_or_create(user=request.user)
        user_activity.interaction = (
            f"{user_activity.interaction}, {event.event_tag}"
            if user_activity.interaction
            else event.event_tag
        )
        user_activity.save()

    return render(request, "event_detail.html", {"event": event})


def events_by_tag(request, event_tag):
    """Display all events under a specific event_tag"""
    if event_tag == "Upcoming":
        events = Event.objects.all().order_by("date")
    else:
        events = Event.objects.filter(event_tag=event_tag).order_by("date")

    # Set up pagination
    paginator = Paginator(events, 6)
    page_number = request.GET.get("page")
    events = paginator.get_page(page_number)

    return render(
        request, "events_by_tag.html", {"events": events, "event_tag": event_tag}
    )


def search(request):
    """Searching Event"""
    query = request.GET.get("q")
    if not query:
        return redirect("users:home")

    events = Event.objects.filter(
        Q(event_name__icontains=query) | Q(event_tag__icontains=query)
    ).order_by("date")

    # Store search history in UserActivity
    if request.user.is_authenticated:
        user_activity, created = UserProfile.objects.get_or_create(user=request.user)
        user_activity.search_history = (
            f"{user_activity.search_history}, {query}"
            if user_activity.search_history
            else query
        )
        user_activity.save()

    paginator = Paginator(events, 6)
    page_number = request.GET.get("page")
    events = paginator.get_page(page_number)

    return render(request, "search_results.html", {"events": events, "query": query})


def signup(request):
    """Signup Page for User Registration"""

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
    else:
        form = CustomUserCreationForm()
        form.fields["username"].help_text = ""
        form.fields["email"].help_text = ""
        form.fields["password1"].help_text = ""
        form.fields["password2"].help_text = ""
        if "usable_password" in form.fields:
            del form.fields["usable_password"]
    return render(request, "registration/signup.html", {"form": form})

users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Event Recommendations</title>
        <link rel="stylesheet" href="{% static 'home.css' %}">
        <link rel="icon" href="{% static 'images/icon.png' %}" type="image/png">
        <script>
            function validateSearchForm() {
                var searchInput = document.getElementById("search-input").value.trim();
                if (searchInput === "") {
                    return false;
                }
                return true;
            }
        </script>
    </head>
    <body>
        <div class="main-header">
            <img src="{% static 'images/logo.png' %}">
            <h3>Hey, {% if user.is_authenticated %}{{ user.userprofile.first_name|default:user.username }}{% else %}there!{% endif %}</h3>
            <form class="search-form" method="GET" action="{% url 'users:search' %}">
                <input type="text" id="search-input" name="q" placeholder="Search events..." required/>
            </form>
            <form method="GET" action="{% url 'users:events_by_city' %}" class="city-dropdown-form">
                <select name="city" onchange="this.form.submit()">
                    <option value="">Select City</option>
                    {% for city in cities %}
                        <option value="{{ city }}" {% if city == selected_city %}selected{% endif %}>{{ city }}</option>
                    {% endfor %}
                </select>
            </form>
            <a class="home" href="{% url 'users:home' %}">Home</a>
            <div class="dropdown">
                <button>Account</button>
                <div class="dropdown-content">
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}">Profile</a>
                        <form method="POST" action="{% url 'users:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <a href="#" onclick="this.closest('form').submit();">Logout</a>
                        </form>
                    {% else %}
                        <a href="{% url 'users:login' %}">Login</a>
                        <a href="{% url 'users:signup' %}">SignUp</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% block content %}
        <!-- Page-specific content will be inserted here -->
        {% endblock %}

        <footer class="main-footer">
            <p>&copy; 2024 Local Event Finder. All rights reserved.</p>
        </footer>
    </body>
</html>

users/templates/event_detail.html
{% extends "base.html" %}

{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if not user.is_authenticated %}
        document.querySelectorAll('.next-button').forEach(button => {
            button.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the default action
                document.getElementById('login-popup').style.display = 'block';
            });
        });
    
        document.getElementById('close-popup').addEventListener('click', function() {
            document.getElementById('login-popup').style.display = 'none';
        });
        {% endif %}
    });
</script>

<div class="event-detail-container1">
    <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
    <div class="event-detail1">
        <h2>{{ event.event_name }}</h2>
        <p>{{ event.date }} | {{event.time}} | {{ event.event_tag }}</p>
        <h3>Location:</h3>
        <p>{{ event.location }}</p>
        <div class="event-booking">
            <h3>click here to book ticket</h3>
            {% if user.is_authenticated %}
                <a href="{{event.booking_url}}" class="next-button">Book</a>
            {% else %}
                <a href="#" class="next-button">Book</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="event-detail-container2">
    <div class="event-detail2">
        <h3>About:</h3>
        <p>{{ event.description }}</p>
    </div>
</div>

<!-- Popup Modal for Login Alert -->
<div id="login-popup" class="popup">
    <div class="popup-content">
        <span id="close-popup" class="close">&times;</span>
        <p>You need to be login to book tickets.</p>
        <a href="{% url 'users:login' %}?next={{ request.path }}">Login</a>
    </div>
</div>

{% endblock %}

users/templates/events_by_city.html
{% extends "base.html" %}
{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if not user.is_authenticated %}
        // Select the buttons for Next and Last pagination
        const buttons = document.querySelectorAll('.next-button, .last-button');

        // Attach event listeners to both Next and Last buttons
        buttons.forEach(button => {
            button.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the default action
                document.getElementById('login-popup').style.display = 'block';
            });
        });

        document.getElementById('close-popup').addEventListener('click', function() {
            document.getElementById('login-popup').style.display = 'none';
        });
        {% endif %}
    });
</script>

<section class="events-section">
    <div class="section-header">
        <h2>Upcoming Events in {{ selected_city }}</h2>
    </div>
    {% if events %}
        <div class="events-grid-container">
            {% for event in events %}
                <a href="{% url 'users:event_detail' event.id %}" class="event-card">
                    <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
                    <div class="event-content">
                        <h5>{{ event.event_name }}</h5>
                        <p>{{ event.event_tag }}, {{ event.city }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <!-- Pagination Controls -->
        <div class="pagination">
            <span class="step-links">
                {% if events.has_previous %}
                    <a href="?city={{ selected_city }}&page=1">First</a>
                    <a href="?city={{ selected_city }}&page={{ events.previous_page_number }}">Previous</a> 
                {% endif %}

                <span class="current">
                    Page {{ events.number }} of {{ events.paginator.num_pages }}
                </span>

                {% if events.has_next %}
                    <a href="?city={{ selected_city }}&page={{ events.next_page_number }}" class="next-button">Next</a>
                    <a href="?city={{ selected_city }}&page={{ events.paginator.num_pages }}" class="last-button">Last</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <p>No events found in {{ selected_city }}.</p>
    {% endif %}
</section>

<!-- Popup Modal for Login Alert -->
<div id="login-popup" class="popup">
    <div class="popup-content">
        <span id="close-popup" class="close">&times;</span>
        <p>You need to be logged in to navigate through the events.</p>
        <a href="{% url 'users:login' %}?next={{ request.path }}">Login</a>
    </div>
</div>

{% endblock %}

users/templates/events_by_tag.html
{% extends "base.html" %}

{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if not user.is_authenticated %}
        // Select the buttons for Next and Last pagination
        const buttons = document.querySelectorAll('.next-button, .last-button');
        
        // Attach event listeners to both Next and Last buttons
        buttons.forEach(button => {
            button.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent the default action
                document.getElementById('login-popup').style.display = 'block';
            });
        });
    
        document.getElementById('close-popup').addEventListener('click', function() {
            document.getElementById('login-popup').style.display = 'none';
        });
        {% endif %}
    });
</script>

<section class="events-section">
    <h2>{{ event_tag }} Events</h2>
    <div class="events-grid-container">
        {% for event in events %}
            <a href="{% url 'users:event_detail' event.id %}" class="event-card">
                <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
                <div class="event-content">
                    <h5>{{ event.event_name }}</h5>
                    <p>{{ event.city }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
    <!-- Pagination Controls -->
    <div class="pagination">
        <span class="step-links">
            {% if events.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ events.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ events.number }} of {{ events.paginator.num_pages }}
            </span>

            {% if events.has_next %}
                <a href="?page={{ events.next_page_number }}" class="next-button">Next</a>
                <a href="?page={{ events.paginator.num_pages }}" class="last-button">Last</a>
            {% endif %}
        </span>
    </div>
</section>

<!-- Popup Modal for Login Alert -->
<div id="login-popup" class="popup">
    <div class="popup-content">
        <span id="close-popup" class="close">&times;</span>
        <p>You need to be logged in to navigate through the events.</p>
        <a href="{% url 'users:login' %}?next={{ request.path }}">Login</a>
    </div>
</div>

{% endblock %}

users/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        function scroll(container, direction) {
            const scrollAmount = 440;
            container.scrollBy(direction === 'left' ? -scrollAmount : scrollAmount, 0);
        }

        document.querySelectorAll('.cover').forEach(cover => {
            const leftButton = cover.querySelector('.left');
            const rightButton = cover.querySelector('.right');
            const container = cover.querySelector('.events-container');
            
            if (leftButton && rightButton && container) {
                leftButton.addEventListener('click', function() {
                    scroll(container, 'left');
                });

                rightButton.addEventListener('click', function() {
                    scroll(container, 'right');
                });
            }
        });
        {% if not user.is_authenticated %}
            document.querySelectorAll('.view-all-link').forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault(); // Prevent the default link action
                    document.getElementById('login-popup').style.display = 'block';
                });
            });

            document.getElementById('close-popup').addEventListener('click', function() {
                document.getElementById('login-popup').style.display = 'none';
            });
        {% endif %}
    });
</script>

<!-- Popup Modal for Login Alert -->
<div id="login-popup" class="popup">
    <div class="popup-content">
        <span id="close-popup" class="close">&times;</span>
        <p>You need to be logged in to view all events.</p>
        <a href="{% url 'users:login' %}?next={{ request.path }}">Login</a>
    </div>
</div>

<section class="events-section">
    <div class="section-header">
        <h2>Upcoming Events</h2>
        {% if user.is_authenticated %}
            <a href="{% url 'users:events_by_tag' 'Upcoming' %}" class="view-all-link">view all</a>
        {% else %}
            <a href="#" class="view-all-link">view all</a>
        {% endif %}
    </div>
    <div class="cover">
        <button class="left">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
            </svg>
        </button>
        <div class="events-container">
            {% for event in events %}
                <a href="{% url 'users:event_detail' event.id %}" class="event-card">
                    <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
                    <div class="event-content">
                        <h5>{{ event.event_name }}</h5>
                        <p>{{ event.event_tag }}, {{ event.city }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <button class="right">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
            </svg>
        </button>
    </div>
</section>

<section class="events-section">
    <div class="section-header">
        <h2>Search Events By Genre</h2>
    </div>
    <div class="tag-container">
        {% for tag, events in events_by_tag.items %}
        <a href="{% url 'users:events_by_tag' tag %}" class="tag-card">
            <img src="{% static 'images/' %}{{ tag|lower|slice:"4" }}.png" alt="{{ tag }}">
        </a>
        {% endfor %}
    </div>
</section>

{% if user.is_authenticated and recommended_events %}
<section class="events-section">
    <div class="section-header">
        <h2>Recommended for You</h2>
    </div>
    <div class="cover">
        <button class="left">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
            </svg>
        </button>
        <div class="events-container">
            {% for event in recommended_events %}
                <a href="{% url 'users:event_detail' event.id %}" class="event-card">
                    <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
                    <div class="event-content">
                        <h5>{{ event.event_name }}</h5>
                        <p>{{ event.event_tag }}, {{ event.city }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <button class="right">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
            </svg>
        </button>
    </div>
</section>
{% endif %}

{% for tag, events in events_by_tag.items %}
<section class="events-section">
    <div class="section-header">
        <h2>{{ tag }}</h2>
        {% if user.is_authenticated %}
            <a href="{% url 'users:events_by_tag' tag %}" class="view-all-link">view all</a>
        {% else %}
            <a href="#" class="view-all-link">view all</a>
        {% endif %}
    </div>
    <div class="cover">
        <button class="left">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
            </svg>
        </button>
        <div class="events-container">
            {% for event in events %}
                <a href="{% url 'users:event_detail' event.id %}" class="event-card">
                    <img src="{{ event.image_url }}" alt="{{ event.event_name }}">
                    <div class="event-content">
                        <h5>{{ event.event_name }}</h5>
                        <p>{{ event.event_tag }}, {{ event.city }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <button class="right">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
            </svg>
        </button>
    </div>
</section>
{% endfor %}
{% endblock %}

users/templates/profile.html
{% load static %} 
<!DOCTYPE html>
 <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Event Recommendations</title>
        <link rel="stylesheet" href="{% static 'profile.css' %}">
    </head>
    <body>
        <div class="main-header">
            <img src="{% static 'images/logo.png' %}">
            <h3>Hey, {% if user.is_authenticated %}{{ user.userprofile.first_name|default:user.username }}{% else %}there!{% endif %}</h3>
            <div class="nav-content">
                <a href="{% url 'users:home' %}">Home</a>
                <form method="POST" action="{% url 'users:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <a href="#" onclick="this.closest('form').submit();">Logout</a>
                </form>
            </div>
        </div>
        <div class="container">
            <h1>Update Profile</h1>
            <!-- Display the current profile image if it exists -->
            <div class="profile-picture">
                {% if profile_form.instance.profile_picture %}
                    <img src="{{ profile_form.instance.profile_picture.url }}" alt="Profile Picture" style="width:150px; height:150px; border-radius:50%;">
                {% else %}
                    <img src="{% static 'images/default-profile.png' %}" alt="Default Profile Picture" style="width:150px; height:150px; border-radius:50%;">
                {% endif %}
            </div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-grp">
                    <!-- Username Field -->
                    <div class="form-group">
                        <label for="id_username">Username:</label>
                        {{ user_form.username }}
                    </div>

                    <!-- Email Field (disabled) -->
                    <div class="form-group" >
                        <label for="id_email" disabled=True>Email:</label>
                        {{ user_form.email }}
                    </div>
                </div>
                <div class="form-grp">
                    <div class="form-group">
                        <label for="id_first_name">First Name:</label>
                        {{ profile_form.first_name }}
                    </div>
                        
                    <div class="form-group">
                        <label for="id_last_name">Last Name:</label>
                        {{ profile_form.last_name }}
                    </div>
                </div>
                <div class="form-grp">
                    <!-- Profile Picture Field -->
                    <div class="form-group">
                        <label for="id_profile_picture">Profile Picture:</label>
                        {{ profile_form.profile_picture }}
                    </div>
                    <!-- Location Field -->
                    <div class="form-group">
                        <label for="id_location">Location:</label>
                        {{ profile_form.location }}
                    </div>
                </div>
                <!-- Submit Button -->
                <div class="form-group">
                    <button type="submit">Update Profile</button>
                </div>
            </form>
        </div>       
    </body>
 </html>